version: "3"
services:
    web:
        image: craigderington/flaskdock:latest
        ports:
            - "8000:8000"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"  
